#!/bin/bash
docker-compose up --build -d
echo -e ''
echo -e 'EXPLOITATION'
echo -e ''
echo -e 'Visit \e[32mhttp://localhost:8081 \e[0mto access the vulnerable web application'
echo -e 'Use http://attackerserver-flaskxxe:8888 to access the attacker hosting server from the vulnerable web app.'
echo -e ''
echo -e 'DEBUGGING'
echo -e ''
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| docker containers               | How to access                                                  |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| attacker server (file hosting ) | docker container exec -it attackerserver-flaskxxe bash         |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| vulnerable server               | docker container exec -it vulnerableserver-flaskxxe bash       |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
echo -e '| aws metadata simulator          | docker container exec -it aws-metadata-simulator-flaskxxe bash |'
echo -e '+---------------------------------+----------------------------------------------------------------+'
