version: "3.8"
services:

  vulnserver:
    # contains the vulnerable code to exploit
    container_name: vulnerableserver-jaxb
    build:
      context: ./vulnserver/tomcat-deployment/
    ports:
      - 8083:8080
    networks:
      - xxejaxbdemo
    # to allow IP FORWARDING
    cap_add:
      - NET_ADMIN

  attackerserver: 
    # attacker's webservice to retrieve external DTD files
    # http://attackerserver-jaxb:8888 will be resolvable in xxejaxbdemo network.
    container_name: attackerserver-jaxb
    build:
      context: ./attackerserver
      args:
        LPORT: 8888
    networks:
      - xxejaxbdemo

  aws-metadata-simulator: 
    # use to demonstrate SSRF's impact in AWS cloud
    container_name: aws-metadata-simulator-jaxb
    build:
      context: ./aws-metadata-simulator/
    networks:
      - xxejaxbdemo

networks:
  xxejaxbdemo:
    driver: "bridge"
