apiVersion: v1
kind: Service
metadata:
  name: attackerserver-service
spec:
  type: ClusterIP
  selector:
    app: attackerserver
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attackerserver-deployment
spec:
  selector:
    matchLabels:
      app: attackerserver
  template:
    metadata:
      labels:
        app: attackerserver
    spec:
      containers:
        - name: attackerserver
          image: python-flask-xxe_attackerserver:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: simulator-service
spec:
  type: ClusterIP
  selector:
    app: metadata-simulator
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-simulator-deployment
spec:
  selector:
    matchLabels:
      app: metadata-simulator
  template:
    metadata:
      labels:
        app: metadata-simulator
    spec:
      containers:
        - name: metadata-simulator
          image: python-flask-xxe_aws-metadata-simulator:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8111
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerableserver-service
spec:
  type: NodePort
  selector:
    app: vulnerableserver
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerableserver-deployment
spec:
  selector:
    matchLabels:
      app: vulnerableserver
  # replicas: 2
  template:
    metadata:
      labels:
        app: vulnerableserver
    spec:
      containers:
        - name: vulnerableserver
          image: python-flask-xxe_vulnserver:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8081
          env:
          - name: ATTACKER_HOSTNAME
            value: "attackerserver-service.default.svc.cluster.local"
          - name: SIMULATOR_HOSTNAME
            value: "simulator-service.default.svc.cluster.local"
---
